### ISSUE TITLE
error[E0463]: can't find crate for `exonum`

### ISSUE THREAD

**Issue by lazaridiscom** [exonum/cryptocurrency#50]
On windows10

```
git clone https://github.com/exonum/exonum.git
cd exonum
cargo test --manifest-path exonum/Cargo.toml
```

All fine, except one network-timeout test.

Then i got the example demo running (listening on port 8000). As i cannot start the sh-scripts, I tried with `demo.rs`.

`rustc demo.rs` results in an error:

`error[E0463]: can't find crate for `exonum``

Whats wrong?

**Comment by lazaridiscom** [comment]
Just looked at the code and realized that `demo.rs` is not a "client-access", but the example-launch code.

I assume that there are currently only the *.sh scripts (wallets_info.sh, test.sh) which access the demo?

**Comment by slowli** [comment]
Regarding your original question: `rustc demo.rs` isn't *supposed* to work because it lacks access to dependency management tooling brought by the Rust's dependency manager, cargo (in particular, `rustc` on its own doesn't know where to locate the external dependencies of your code, hence the error). You need to use `cargo build --example demo` to build the demo instead.

> I assume that there are currently only the *.sh scripts (wallets_info.sh, test.sh) which access the demo?

These scripts simplify things, but you can access the demo via any tool that knows how to send GET and POST HTTP requests and process responses. The tutorial and the scripts both use `curl` as this tool. Windows PowerShell has [`Invoke-WebRequest`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-webrequest?view=powershell-5.1) tool for this purpose, so it should be possible to recreate `test.sh` for PowerShell (I'll create an issue for this rn). Additionally, we are in the process of creating a new tutorial focused on client interaction with Exonum, in course of which a web app would be built to interact with the current demo. Preliminary, it will be ready in 1 to 1.5 months.

**Comment by lazaridiscom** [comment]
closing (non-issue)

**Comment by lazaridiscom** [comment]
followup: #51
